trigger:
  branches:
    include: ['*']
  paths:
    include: ['*']

steps:
- checkout: self
  persistCredentials: true

- bash: |
    ls -lA
    T=`date '+boza_%F_%H-%M-%S'`
    echo "##vso[build.updatebuildnumber]$T"
    git tag "$T"
    git push --tags
