trigger:
  branches:
    include: ['*']
  paths:
    include: ['*']

steps:
- checkout: self
  persistCredentials: true

- bash: |
    set -e
    NAME=vapt
    T=`date '+%F_%H-%M-%S'`
    echo "##vso[build.updatebuildnumber]$T"
    git tag "$NAME_$T"
    git push --tags
  displayName: add tag
