trigger:
  branches:
    include: ['*']
  paths:
    include: ['*']

steps:
- checkout: self
  persistCredentials: true

- bash: |
    ls -lA
    TIME=`date '+%F %T'`
    echo "##vso[build.updatebuildnumber]$TIME"
    git tag "boza $TIME"
    git push --tags
